/* 
 * Anomaly Detector Cognitive Service API
 *
 * The Anomaly Detector Service detects anomalies automatically in time series data. It supports two functionalities, one is for detecting the whole series with model trained by the time series, another is detecting last point with model trained by points before. By using this service, developers can discover incidents and establish a logic flow for root cause analysis.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChangePointDetectRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangePointDetectRequestTests
    {
        // TODO uncomment below to declare an instance variable for ChangePointDetectRequest
        //private ChangePointDetectRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangePointDetectRequest
            //instance = new ChangePointDetectRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangePointDetectRequest
        /// </summary>
        [Test]
        public void ChangePointDetectRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangePointDetectRequest
            //Assert.IsInstanceOfType<ChangePointDetectRequest> (instance, "variable 'instance' is a ChangePointDetectRequest");
        }


        /// <summary>
        /// Test the property 'Series'
        /// </summary>
        [Test]
        public void SeriesTest()
        {
            // TODO unit test for the property 'Series'
        }
        /// <summary>
        /// Test the property 'Granularity'
        /// </summary>
        [Test]
        public void GranularityTest()
        {
            // TODO unit test for the property 'Granularity'
        }
        /// <summary>
        /// Test the property 'CustomInterval'
        /// </summary>
        [Test]
        public void CustomIntervalTest()
        {
            // TODO unit test for the property 'CustomInterval'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'StableTrendWindow'
        /// </summary>
        [Test]
        public void StableTrendWindowTest()
        {
            // TODO unit test for the property 'StableTrendWindow'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Test]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }

    }

}
