/* 
 * Anomaly Detector Cognitive Service API
 *
 * The Anomaly Detector Service detects anomalies automatically in time series data. It supports two functionalities, one is for detecting the whole series with model trained by the time series, another is detecting last point with model trained by points before. By using this service, developers can discover incidents and establish a logic flow for root cause analysis.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EntireDetectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntireDetectResponseTests
    {
        // TODO uncomment below to declare an instance variable for EntireDetectResponse
        //private EntireDetectResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntireDetectResponse
            //instance = new EntireDetectResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntireDetectResponse
        /// </summary>
        [Test]
        public void EntireDetectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntireDetectResponse
            //Assert.IsInstanceOfType<EntireDetectResponse> (instance, "variable 'instance' is a EntireDetectResponse");
        }


        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'ExpectedValues'
        /// </summary>
        [Test]
        public void ExpectedValuesTest()
        {
            // TODO unit test for the property 'ExpectedValues'
        }
        /// <summary>
        /// Test the property 'UpperMargins'
        /// </summary>
        [Test]
        public void UpperMarginsTest()
        {
            // TODO unit test for the property 'UpperMargins'
        }
        /// <summary>
        /// Test the property 'LowerMargins'
        /// </summary>
        [Test]
        public void LowerMarginsTest()
        {
            // TODO unit test for the property 'LowerMargins'
        }
        /// <summary>
        /// Test the property 'IsAnomaly'
        /// </summary>
        [Test]
        public void IsAnomalyTest()
        {
            // TODO unit test for the property 'IsAnomaly'
        }
        /// <summary>
        /// Test the property 'IsNegativeAnomaly'
        /// </summary>
        [Test]
        public void IsNegativeAnomalyTest()
        {
            // TODO unit test for the property 'IsNegativeAnomaly'
        }
        /// <summary>
        /// Test the property 'IsPositiveAnomaly'
        /// </summary>
        [Test]
        public void IsPositiveAnomalyTest()
        {
            // TODO unit test for the property 'IsPositiveAnomaly'
        }

    }

}
