#
# Publish Microsoft.Azure.IIoT.Azure.Deployment Executables on MacOS
#
parameters:
  runtime: 'osx-x64'
  poolName: 'Hosted macOS'

jobs:
- job: iiot_deployment_mac
  displayName: Generate MacOS Executables
  pool:
    name: ${{ parameters.poolName }}
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 3.1.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PowerShell@2
    displayName: Versioning
    name: setVersionInfo
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'azure/Microsoft.Azure.IIoT.Azure.Deployment/src/Microsoft.Azure.IIoT.Azure.Deployment.csproj'
      arguments: '--runtime ${{ parameters.runtime }} --configuration Release -p:PublishSingleFile=true --self-contained --output $(Build.ArtifactStagingDirectory)/${{ parameters.runtime }}'
      zipAfterPublish: false
  - task: CmdLine@2
    displayName: 'Generate MD5 Checksum'
    inputs:
      script:  md5 -r Microsoft.Azure.IIoT.Azure.Deployment Microsoft.Azure.IIoT.Azure.Deployment.pdb > Microsoft.Azure.IIoT.Azure.Deployment.md5
      workingDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Azure.Deployment
  - task: ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      path: $(Build.ArtifactStagingDirectory)/
      artifact: iiot_deployment_release_$(setVersionInfo.Version_Full)_${{ parameters.runtime }}
  - task: AzureCLI@2
    displayName: 'Copy to Blob'
    condition: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}
    inputs:
      azureSubscription: azureiiot-storage
      scriptType: pscore
      workingDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Azure.Deployment
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload --account-name azureiiot --container-name binaries -f Microsoft.Azure.IIoT.Azure.Deployment --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Azure.Deployment
        az storage blob upload --account-name azureiiot --container-name binaries -f Microsoft.Azure.IIoT.Azure.Deployment.pdb --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Azure.Deployment.pdb
        az storage blob upload --account-name azureiiot --container-name binaries -f Microsoft.Azure.IIoT.Azure.Deployment.md5 --name ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}/$(setVersionInfo.Version_Prefix)/${{ parameters.runtime }}/Microsoft.Azure.IIoT.Azure.Deployment.md5
