/* 
 * Anomaly Detector Cognitive Service API
 *
 * The Anomaly Detector Service detects anomalies automatically in time series data. It supports two functionalities, one is for detecting the whole series with model trained by the time series, another is detecting last point with model trained by points before. By using this service, developers can discover incidents and establish a logic flow for root cause analysis.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChangePointDetectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangePointDetectResponseTests
    {
        // TODO uncomment below to declare an instance variable for ChangePointDetectResponse
        //private ChangePointDetectResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangePointDetectResponse
            //instance = new ChangePointDetectResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangePointDetectResponse
        /// </summary>
        [Test]
        public void ChangePointDetectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangePointDetectResponse
            //Assert.IsInstanceOfType<ChangePointDetectResponse> (instance, "variable 'instance' is a ChangePointDetectResponse");
        }


        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'IsChangePoint'
        /// </summary>
        [Test]
        public void IsChangePointTest()
        {
            // TODO unit test for the property 'IsChangePoint'
        }
        /// <summary>
        /// Test the property 'ConfidenceScores'
        /// </summary>
        [Test]
        public void ConfidenceScoresTest()
        {
            // TODO unit test for the property 'ConfidenceScores'
        }

    }

}
