/* 
 * Anomaly Detector Cognitive Service API
 *
 * The Anomaly Detector Service detects anomalies automatically in time series data. It supports two functionalities, one is for detecting the whole series with model trained by the time series, another is detecting last point with model trained by points before. By using this service, developers can discover incidents and establish a logic flow for root cause analysis.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LastDetectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LastDetectResponseTests
    {
        // TODO uncomment below to declare an instance variable for LastDetectResponse
        //private LastDetectResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LastDetectResponse
            //instance = new LastDetectResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LastDetectResponse
        /// </summary>
        [Test]
        public void LastDetectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LastDetectResponse
            //Assert.IsInstanceOfType<LastDetectResponse> (instance, "variable 'instance' is a LastDetectResponse");
        }


        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'SuggestedWindow'
        /// </summary>
        [Test]
        public void SuggestedWindowTest()
        {
            // TODO unit test for the property 'SuggestedWindow'
        }
        /// <summary>
        /// Test the property 'ExpectedValue'
        /// </summary>
        [Test]
        public void ExpectedValueTest()
        {
            // TODO unit test for the property 'ExpectedValue'
        }
        /// <summary>
        /// Test the property 'UpperMargin'
        /// </summary>
        [Test]
        public void UpperMarginTest()
        {
            // TODO unit test for the property 'UpperMargin'
        }
        /// <summary>
        /// Test the property 'LowerMargin'
        /// </summary>
        [Test]
        public void LowerMarginTest()
        {
            // TODO unit test for the property 'LowerMargin'
        }
        /// <summary>
        /// Test the property 'IsAnomaly'
        /// </summary>
        [Test]
        public void IsAnomalyTest()
        {
            // TODO unit test for the property 'IsAnomaly'
        }
        /// <summary>
        /// Test the property 'IsNegativeAnomaly'
        /// </summary>
        [Test]
        public void IsNegativeAnomalyTest()
        {
            // TODO unit test for the property 'IsNegativeAnomaly'
        }
        /// <summary>
        /// Test the property 'IsPositiveAnomaly'
        /// </summary>
        [Test]
        public void IsPositiveAnomalyTest()
        {
            // TODO unit test for the property 'IsPositiveAnomaly'
        }

    }

}
