/* 
 * Anomaly Detector Cognitive Service API
 *
 * The Anomaly Detector Service detects anomalies automatically in time series data. It supports two functionalities, one is for detecting the whole series with model trained by the time series, another is detecting last point with model trained by points before. By using this service, developers can discover incidents and establish a logic flow for root cause analysis.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceStatusTests
    {
        // TODO uncomment below to declare an instance variable for ServiceStatus
        //private ServiceStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceStatus
            //instance = new ServiceStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceStatus
        /// </summary>
        [Test]
        public void ServiceStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceStatus
            //Assert.IsInstanceOfType<ServiceStatus> (instance, "variable 'instance' is a ServiceStatus");
        }


        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property 'ApiStatus'
        /// </summary>
        [Test]
        public void ApiStatusTest()
        {
            // TODO unit test for the property 'ApiStatus'
        }
        /// <summary>
        /// Test the property 'ApiStatusMessage'
        /// </summary>
        [Test]
        public void ApiStatusMessageTest()
        {
            // TODO unit test for the property 'ApiStatusMessage'
        }

    }

}
